# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_name', models.CharField(blank=True, max_length=200)),
                ('extra_cost', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(default=0)),
                ('total_cost', models.IntegerField(default=0)),
                ('recent_item_cost', models.IntegerField(default=0)),
                ('name_recent_item', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
