# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messautomation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hall',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='', max_length=10),
        ),
    ]
