# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messautomation', '0002_auto_20160920_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name_recent_item',
            new_name='recent_item_name',
        ),
    ]
