# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messautomation', '0003_auto_20160920_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='all_items_cost',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AddField(
            model_name='student',
            name='all_items_name',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AddField(
            model_name='student',
            name='all_items_quantity',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AddField(
            model_name='student',
            name='all_items_total_cost',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
