# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messautomation', '0004_auto_20160920_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='all_items_date',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
