# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messautomation', '0005_student_all_items_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
