# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messautomation', '0006_extras_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extras',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
