# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messautomation', '0007_auto_20160923_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='num',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
