# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messautomation', '0008_extras_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
