# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-25 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messautomation', '0009_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=10)),
                ('time_taken', models.CharField(default='', max_length=100)),
                ('total_cost', models.CharField(default='', max_length=100)),
                ('ran_id', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='token_ids',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
