# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messautomation', '0010_auto_20170325_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='item_taken',
            field=models.CharField(default='', max_length=100),
        ),
    ]
